#!/bin/bash
#
# ks-vaudit-configure                    Startup script for ks-vaudit-configure
#
# chkconfig: - 85 15
# description: auto run
# processname: ks-vaudit-configure
#

. /etc/init.d/functions

RETVAL=0
procname=ks-vaudit-configure

start(){
        __pids_var_run "${procname}" "$pid_file"
        if [ -z "$pid_file" -a -z "$pid" ]; then
                pid="$(__pids_pidof "${procname}")"
        fi

        if [ -n "$pid" ] ; then
                echo "service is already running!!!"
                exit 0
        fi

	export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/ks-vaudit/Qt5.7.1/5.7/gcc_64/lib
        /usr/bin/${procname} &
        if [ $? -eq 0 ];then
                echo_success
        else
                echo_failure
        fi
        echo "Start ${procname} service: "
}

stop(){
        killproc ${procname}
        echo "Shutting down ${procname}: "
}

rhstatus() {
        status ${procname}
}

restart() {
        stop
        start
}

case $1 in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        rhstatus
        ;;
  restart)
        restart
        ;;
  *)
        echo 'service accept arguments start|stop|status|restart'
        exit 2
esac
