#!/bin/bash
#
# ks-vaudit-monitor                    Startup script for ks-vaudit-monitor
#
# chkconfig: - 85 15
# description: auto run
# processname: ks-vaudit-monitor
#

. /etc/init.d/functions

RETVAL=0
procname=ks-vaudit-monitor
lockfile=/var/lock/subsys/$procname

start(){
        __pids_var_run "${procname}" "$pid_file"
        if [ -z "$pid_file" -a -z "$pid" ]; then
                pid="$(__pids_pidof "${procname}")"
        fi

        if [ -n "$pid" ] ; then
                echo "service is already running!!!"
                exit 0
        fi

        export LD_LIBRARY_PATH=/usr/local/lib64:/usr/local/ks-vaudit/Qt5.7.1/5.7/gcc_64/lib:$LD_LIBRARY_PATH
        /usr/bin/${procname} &
        RETVAL=$?
        if [ $RETVAL -eq 0 ];then
                echo_success
        else
                echo_failure
        fi
        echo "Start ${procname} service: "
        [ $RETVAL -eq 0 ] && touch $lockfile
        return $RETVAL
}

stop(){
        echo -n $"Shutting down ${procname}: "
        killproc ${procname}
        ps aux | grep /usr/bin/ks-vaudit | grep "ks-vaudit \-\-audit\-" | awk '{print $2}' | xargs kill -2 > /dev/null 2>&1
        RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f $lockfile
        return $RETVAL
}

rhstatus() {
        status ${procname}
}

restart() {
        stop
        start
}

case $1 in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        rhstatus
        ;;
  restart)
        restart
        ;;
  *)
        echo 'service accept arguments start|stop|status|restart'
        exit 2
esac
